version: "3"

services:
  # Backend Service
  book-server:
    image: wisekingdavid/bookstore-server:0.1
    container_name: book-server
    ports:
      - "9000:9000"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/book-postgres-db
      - SPRING_DATASOURCE_USERNAME=book-postgres
      - SPRING_DATASOURCE_PASSWORD=book-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend
      - frontend

  # Frontend Service
  book-client:
    image: wisekingdavid/bookstore-client:0.1
    container_name: book-client

    ports:
      - "4200:80"
    restart: always
    depends_on:
      - book-server
    networks:
      - frontend

  # Database
  PostgreSQL:
    image: postgres
    container_name: book-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=book-postgres
      - POSTGRES_PASSWORD=book-postgres
      - POSTGRES_DB=book-postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  # Prometheus - Scraping monitoring data
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    depends_on:
      - book-server
    networks:
      - backend
      - frontend

  # Grafana - Visualize scraped data from prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: root
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=host.docker.internal
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
